$(function(){new osSlider({pNode:'.slider',cNode:'.slider-main li',speed:2000,autoPlay:true});var bd_height=new Array();var old_key=0;$('.floors').each(function(){bd_height[$(this).index()]=$(this).offset().top;})
$(window).scroll(function(){var slThis=$(this).height();var slTop=$(this).scrollTop();var showHt=slTop+slThis/2;if(showHt>1055){$('#top_search').stop()
$('#top_search').animate({top:'0px'},300);}else{$('#top_search').stop()
$('#top_search').animate({top:'-50px'},200);}
if(showHt>1000&&showHt<4300){$('.floor').show();}else{$('.floor').hide();}
if(showHt>=1160&&showHt<=1750){$('.floor span').removeClass('floor_active')
$('#books').addClass('floor_active')}else if(showHt>=1751&&showHt<=2320){$('.floor span').removeClass('floor_active')
$('#clothing').addClass('floor_active')}else if(showHt>=2328&&showHt<=3000){$('.floor span').removeClass('floor_active')
$('#movement').addClass('floor_active')}else if(showHt>=3005&&showHt<=3680){$('.floor span').removeClass('floor_active')
$('#kids').addClass('floor_active')}else if(showHt>=3682&&showHt<=4300){$('.floor span').removeClass('floor_active')
$('#household').addClass('floor_active')}else{$('.floor span').removeClass('floor_active')}
var key=0;bd_height.map(function(value,index){if(showHt>=value){key=index;}})
if(old_key==key){return false;}else{old_key=key;change_step(key);}})
function change_step(key){var bg_color=$('.floor_icon');var old_top=bg_color.position();var ul_ftop=$('.floor').offset();var li_ftop=$('.floor span').eq(key).offset();var target_top=li_ftop-ul_ftop;bg_color.animate({top:target_top},'fast');}
function change_building(key){var slThis=$(window).height();var target=$('.floors').eq(key).offset().top;target-=slThis/2-1;$('html,body').animate({scrollTop:target});}
$('.floor span').click(function(){var key=$(this).index();change_building(key);})
$('#Top').on('click',function(){$('html, body').animate({scrollTop:0},'slow');})
$('.ebook_left').hide();$('#newBook').show();$('#newBooks').addClass('books_active')
$('#newBooks').on('click mouseover',function(){$('.ebook_title span').removeClass('books_active')
$('#newBooks').addClass('books_active')
$('.ebook_left').hide();$('#newBook').show();})
$('#Ebooks').on('click mouseover',function(){$('.ebook_title span').removeClass('books_active')
$('#Ebooks').addClass('books_active')
$('.ebook_left').hide();$('#Ebook').show();})
$('#Exclusive').on('click mouseover',function(){$('.ebook_title span').removeClass('books_active')
$('#Exclusive').addClass('books_active')
$('.ebook_left').hide();$('#goodMarket').show();})
$('.ebook_right_list img').hide()
$('.ebook_right_list .introduction').hide()
$('.ebook_right_list:first-child').addClass('ebook_right_active')
$('.ebook_right_list:first-child img').show()
$('.ebook_right_list:first-child .introduction').show()
$('.ebook_right_list').on('mouseover',function(){$('.ebook_right_list img').hide()
$('.ebook_right_list .introduction').hide()
$('.ebook_right_list').removeClass('ebook_right_active')
$(this).addClass('ebook_right_active')
$(this).find('img').show()
$(this).find('.introduction').show()})
$('#Underwear,#Menswear,#Shoes').hide();$('#Underwear').show();$('#Underwears').addClass('title_active')
$('#Underwears').on('click mouseover',function(){$('#clothings span').removeClass('title_active')
$('#Underwears').addClass('title_active')
$('#Underwear,#Menswear,#Shoes').hide();$('#Underwear').show();})
$('#Menswears').on('click mouseover',function(){$('#clothings span').removeClass('title_active')
$('#Menswears').addClass('title_active')
$('#Underwear,#Menswear,#Shoes').hide();$('#Menswear').show();})
$('#Shoe').on('click mouseover',function(){$('#clothings span').removeClass('title_active')
$('#Shoe').addClass('title_active')
$('#Underwear,#Menswear,#Shoes').hide();$('#Shoes').show();})
$('#SportsTrend,#Equipment,#FamousBrand').hide();$('#FamousBrand').show();$('#famousBrand').addClass('title_active')
$('#famousBrand').on('click mouseover',function(){$('#movements span').removeClass('title_active')
$('#famousBrand').addClass('title_active')
$('#SportsTrend,#Equipment,#FamousBrand').hide();$('#FamousBrand').show();})
$('#Equipments').on('click mouseover',function(){$('#movements span').removeClass('title_active')
$('#Equipments').addClass('title_active')
$('#SportsTrend,#Equipment,#FamousBrand').hide();$('#Equipment').show();})
$('#sportsTrend').on('click mouseover',function(){$('#movements span').removeClass('title_active')
$('#sportsTrend').addClass('title_active')
$('#SportsTrend,#Equipment,#FamousBrand').hide();$('#SportsTrend').show();})
$('#ChildrenGarment,#BabyOutfif,#ChildrenShoes').hide();$('#ChildrenShoes').show();$('#ChildrenGarments').addClass('title_active')
$('#ChildrenGarments').on('click mouseover',function(){$('#Baby span').removeClass('title_active')
$('#ChildrenGarments').addClass('title_active')
$('#ChildrenGarment,#BabyOutfif,#ChildrenShoes').hide();$('#ChildrenGarment').show();})
$('#Babyoutfif').on('click mouseover',function(){$('#Baby span').removeClass('title_active')
$('#Babyoutfif').addClass('title_active')
$('#ChildrenGarment,#BabyOutfif,#ChildrenShoes').hide();$('#BabyOutfif').show();})
$('#ChildrenShoe').on('click mouseover',function(){$('#Baby span').removeClass('title_active')
$('#ChildrenShoe').addClass('title_active')
$('#ChildrenGarment,#BabyOutfif,#ChildrenShoes').hide();$('#ChildrenShoes').show();})
$('#dot1').addClass('dot_active')
$('#dot2').on('click',function(){$('#dot1,#dot2').removeClass('dot_active')
$('#dot2').addClass('dot_active')
$('#popularize_1').animate({top:'-600px'},1000,)
$('#popularize_2').animate({top:'0px'},1000,)})
$('#dot1').on('click',function(){$('#dot1,#dot2').removeClass('dot_active')
$('#dot1').addClass('dot_active')
$('#popularize_2').animate({top:'600px'},1000,)
$('#popularize_1').animate({top:'0px'},1000,)})})
$(function(){new Vue({el:'#carouselEbook1',data:{mark:0,img:['img/电子书轮播/0729.jpg','img/电子书轮播/0914.jpg','img/电子书轮播/lanqiu.jpg','img/电子书轮播/1.jpg',],time:null},methods:{change(i){this.mark=i;},prev(){this.mark--;if(this.mark===-1){this.mark=3;return}},next(){this.mark++;if(this.mark===4){this.mark=0;return}},autoPlay(){this.mark++;if(this.mark===4){this.mark=0;return}},play(){this.time=setInterval(this.autoPlay,3000);},enter(){console.log('enter')
clearInterval(this.time);},leave(){console.log('leave')
this.play();}},created(){this.play()}})
new Vue({el:'#carouselEbook2',data:{mark:0,img:['img/电子书轮播/2.jpg','img/电子书轮播/3.jpg','img/电子书轮播/5.jpg','img/电子书轮播/9.jpg',],time:null},methods:{change(i){this.mark=i;},prev(){this.mark--;if(this.mark===-1){this.mark=3;return}},next(){this.mark++;if(this.mark===4){this.mark=0;return}},autoPlay(){this.mark++;if(this.mark===4){this.mark=0;return}},play(){this.time=setInterval(this.autoPlay,3000);},enter(){console.log('enter')
clearInterval(this.time);},leave(){console.log('leave')
this.play();}},created(){this.play()}})
new Vue({el:'#carouselEbook3',data:{mark:0,img:['img/电子书轮播/1131.jpg','img/电子书轮播/123145151.jpg','img/电子书轮播/345678.jpg','img/电子书轮播/1.jpg',],time:null},methods:{change(i){this.mark=i;},prev(){this.mark--;if(this.mark===-1){this.mark=3;return}},next(){this.mark++;if(this.mark===4){this.mark=0;return}},autoPlay(){this.mark++;if(this.mark===4){this.mark=0;return}},play(){this.time=setInterval(this.autoPlay,3000);},enter(){console.log('enter')
clearInterval(this.time);},leave(){console.log('leave')
this.play();}},created(){this.play()}})
new Vue({el:'#carouselEbook11',data:{mark:0,img:['img/女装轮播/1.jpg','img/女装轮播/2.jpg','img/女装轮播/3.jpg','img/女装轮播/4.jpg',],time:null},methods:{change(i){this.mark=i;},prev(){this.mark--;if(this.mark===-1){this.mark=3;return}},next(){this.mark++;if(this.mark===4){this.mark=0;return}},autoPlay(){this.mark++;if(this.mark===4){this.mark=0;return}},play(){this.time=setInterval(this.autoPlay,3000);},enter(){console.log('enter')
clearInterval(this.time);},leave(){console.log('leave')
this.play();}},created(){this.play()}})
new Vue({el:'#carouselEbook22',data:{mark:0,img:['img/女装轮播/11.jpg','img/女装轮播/22.jpg','img/女装轮播/33.jpg','img/女装轮播/44.jpg',],time:null},methods:{change(i){this.mark=i;},prev(){this.mark--;if(this.mark===-1){this.mark=3;return}},next(){this.mark++;if(this.mark===4){this.mark=0;return}},autoPlay(){this.mark++;if(this.mark===4){this.mark=0;return}},play(){this.time=setInterval(this.autoPlay,3000);},enter(){console.log('enter')
clearInterval(this.time);},leave(){console.log('leave')
this.play();}},created(){this.play()}})
new Vue({el:'#carouselEbook33',data:{mark:0,img:['img/女装轮播/e.jpg','img/女装轮播/f.jpg','img/女装轮播/h.jpg','img/女装轮播/o.jpg',],time:null},methods:{change(i){this.mark=i;},prev(){this.mark--;if(this.mark===-1){this.mark=3;return}},next(){this.mark++;if(this.mark===4){this.mark=0;return}},autoPlay(){this.mark++;if(this.mark===4){this.mark=0;return}},play(){this.time=setInterval(this.autoPlay,3000);},enter(){console.log('enter')
clearInterval(this.time);},leave(){console.log('leave')
this.play();}},created(){this.play()}})
new Vue({el:'#carouselEbook111',data:{mark:0,img:['img/户外运动轮播/t.jpg','img/户外运动轮播/y.jpg','img/户外运动轮播/u.jpg','img/户外运动轮播/i.jpg',],time:null},methods:{change(i){this.mark=i;},prev(){this.mark--;if(this.mark===-1){this.mark=3;return}},next(){this.mark++;if(this.mark===4){this.mark=0;return}},autoPlay(){this.mark++;if(this.mark===4){this.mark=0;return}},play(){this.time=setInterval(this.autoPlay,3000);},enter(){console.log('enter')
clearInterval(this.time);},leave(){console.log('leave')
this.play();}},created(){this.play()}})
new Vue({el:'#carouselEbook222',data:{mark:0,img:['img/户外运动轮播/q.jpg','img/户外运动轮播/w.jpg','img/户外运动轮播/e.jpg','img/户外运动轮播/r.jpg',],time:null},methods:{change(i){this.mark=i;},prev(){this.mark--;if(this.mark===-1){this.mark=3;return}},next(){this.mark++;if(this.mark===4){this.mark=0;return}},autoPlay(){this.mark++;if(this.mark===4){this.mark=0;return}},play(){this.time=setInterval(this.autoPlay,3000);},enter(){console.log('enter')
clearInterval(this.time);},leave(){console.log('leave')
this.play();}},created(){this.play()}})
new Vue({el:'#carouselEbook333',data:{mark:0,img:['img/户外运动轮播/1.jpg','img/户外运动轮播/2.jpg','img/户外运动轮播/3.jpg','img/户外运动轮播/4.jpg',],time:null},methods:{change(i){this.mark=i;},prev(){this.mark--;if(this.mark===-1){this.mark=3;return}},next(){this.mark++;if(this.mark===4){this.mark=0;return}},autoPlay(){this.mark++;if(this.mark===4){this.mark=0;return}},play(){this.time=setInterval(this.autoPlay,3000);},enter(){console.log('enter')
clearInterval(this.time);},leave(){console.log('leave')
this.play();}},created(){this.play()}})
new Vue({el:'#carouselEbook1111',data:{mark:0,img:['img/童装轮播/1.jpg','img/童装轮播/2.jpg','img/童装轮播/3.jpg','img/童装轮播/4.jpg',],time:null},methods:{change(i){this.mark=i;},prev(){this.mark--;if(this.mark===-1){this.mark=3;return}},next(){this.mark++;if(this.mark===4){this.mark=0;return}},autoPlay(){this.mark++;if(this.mark===4){this.mark=0;return}},play(){this.time=setInterval(this.autoPlay,3000);},enter(){console.log('enter')
clearInterval(this.time);},leave(){console.log('leave')
this.play();}},created(){this.play()}})
new Vue({el:'#carouselEbook2222',data:{mark:0,img:['img/童装轮播/z.jpg','img/童装轮播/x.jpg','img/童装轮播/c.jpg','img/童装轮播/v.jpg',],time:null},methods:{change(i){this.mark=i;},prev(){this.mark--;if(this.mark===-1){this.mark=3;return}},next(){this.mark++;if(this.mark===4){this.mark=0;return}},autoPlay(){this.mark++;if(this.mark===4){this.mark=0;return}},play(){this.time=setInterval(this.autoPlay,3000);},enter(){console.log('enter')
clearInterval(this.time);},leave(){console.log('leave')
this.play();}},created(){this.play()}})
new Vue({el:'#carouselEbook3333',data:{mark:0,img:['img/童装轮播/m.jpg','img/童装轮播/n.jpg','img/童装轮播/b.jpg','img/童装轮播/v.jpg',],time:null},methods:{change(i){this.mark=i;},prev(){this.mark--;if(this.mark===-1){this.mark=3;return}},next(){this.mark++;if(this.mark===4){this.mark=0;return}},autoPlay(){this.mark++;if(this.mark===4){this.mark=0;return}},play(){this.time=setInterval(this.autoPlay,3000);},enter(){console.log('enter')
clearInterval(this.time);},leave(){console.log('leave')
this.play();}},created(){this.play()}})})